apiVersion: v2
name: eraser
description: A Helm chart for Eraser
type: application
version: 1.4.0
appVersion: v1.4.0
home: https://github.com/eraser-dev/eraser
sources:
  - https://github.com/eraser-dev/eraser.git
