apiVersion: v2
name: eraser
description: A Helm chart for Eraser
type: application
version: 0.2.0
appVersion: v0.2.0
home: https://github.com/Azure/eraser
sources:
  - https://github.com/Azure/eraser.git
