# permissions for end users to view imagejobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imagejob-viewer-role
rules:
- apiGroups:
  - batch.k8s.io
  resources:
  - imagejobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.k8s.io
  resources:
  - imagejobs/status
  verbs:
  - get
