# permissions for end users to view eraserconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: eraserconfig-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: eraser
    app.kubernetes.io/part-of: eraser
    app.kubernetes.io/managed-by: kustomize
  name: eraserconfig-viewer-role
rules:
- apiGroups:
  - eraser.sh.azure-eraser.io
  resources:
  - eraserconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - eraser.sh.azure-eraser.io
  resources:
  - eraserconfigs/status
  verbs:
  - get
