apiVersion: eraser.sh/v1alpha1
kind: ImageJob
metadata:
  name: imagejob-sample
spec:
  template:
    spec:
      template:
        spec:
          containers:
          - name: eraser
            image: aldaircoronel/remove-images:latest
          restartPolicy: OnFailure
